<template><h1 id="通过备份-etcd-来完美恢复-kubernetes-中的误删数据" tabindex="-1"><a class="header-anchor" href="#通过备份-etcd-来完美恢复-kubernetes-中的误删数据" aria-hidden="true">#</a> 通过备份 Etcd 来完美恢复 Kubernetes 中的误删数据</h1>
<blockquote>
<p>转载自：<a href="https://kubesphere.com.cn/forum/d/3532-etcdkubernetes" target="_blank" rel="noopener noreferrer">Etcd备份数据如何做到完美恢复Kubernetes中误删数据呢<ExternalLinkIcon/></a></p>
</blockquote>
<p>误删或者机器宕机，会导致etcd数据的丢失或某个节点的etcd数据异常时，<strong>请不要慌，认真看完此文，绝对有收获</strong>。当误删时，如何恢复数据，这个操作需求在实际环境当中是不可避免的。以下描述删除两个namespace下的pod，如何恢复对应namespace的数据。</p>
<h2 id="_1-操作环境信息" tabindex="-1"><a class="header-anchor" href="#_1-操作环境信息" aria-hidden="true">#</a> 1 操作环境信息</h2>
<p>3个（master、etcd）+1个node、新建1个namespace下且创建pod和default namespace下创建pod。</p>
<h2 id="_2-前提条件" tabindex="-1"><a class="header-anchor" href="#_2-前提条件" aria-hidden="true">#</a> 2 前提条件</h2>
<p>误删除的数据已在etcd备份</p>
<h2 id="_3-数据环境的模拟" tabindex="-1"><a class="header-anchor" href="#_3-数据环境的模拟" aria-hidden="true">#</a> 3 数据环境的模拟</h2>
<h3 id="_3-1-新建-test-namespace-在该ns下创建pod-创建成功之后-此时这些数据已存在etcd中。" tabindex="-1"><a class="header-anchor" href="#_3-1-新建-test-namespace-在该ns下创建pod-创建成功之后-此时这些数据已存在etcd中。" aria-hidden="true">#</a> 3.1 新建 test namespace，在该ns下创建pod，创建成功之后，此时这些数据已存在etcd中。</h3>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>kubectl get pod <span class="token operator">-</span>n test
NAME                              READY   <span class="token keyword">STATUS</span>    RESTARTS   AGE
details<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">7</span>d78fc5688<span class="token operator">-</span>ntvtd       <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
productpage<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">844495</span>cb4b<span class="token operator">-</span>qn6l9   <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
ratings<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">55</span>ccf46fb4<span class="token operator">-</span>pwqw7       <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
reviews<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">68</span>bb7b8c4f<span class="token operator">-</span>h6vr9       <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h3 id="_3-2-在default-namespace-创建pod-如下所示-创建成功之后-此时这些数据已存在etcd中" tabindex="-1"><a class="header-anchor" href="#_3-2-在default-namespace-创建pod-如下所示-创建成功之后-此时这些数据已存在etcd中" aria-hidden="true">#</a> 3.2 在default namespace 创建pod，如下所示，创建成功之后，此时这些数据已存在etcd中</h3>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>kubectl get pod
NAME                      READY   <span class="token keyword">STATUS</span>    RESTARTS   AGE
nginx<span class="token operator">-</span><span class="token number">6</span>db489d4b7<span class="token operator">-</span>jdfkw    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
nginx1<span class="token operator">-</span><span class="token number">675</span>bf6c9f<span class="token operator">-</span>jndrx    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
nginx2<span class="token operator">-</span><span class="token number">6</span>dfc958b55<span class="token operator">-</span>vgsc4   <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
nginx3<span class="token operator">-</span><span class="token number">8</span>f65b44f9<span class="token operator">-</span><span class="token number">2</span>pk4l    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
nginx4<span class="token operator">-</span><span class="token number">9</span>bb966479<span class="token operator">-</span>svhs6    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
nginx5<span class="token operator">-</span><span class="token number">7</span>d4d998c6c<span class="token operator">-</span><span class="token number">7</span>xlp8   <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
nginx6<span class="token operator">-</span><span class="token number">79444687</span>cf<span class="token operator">-</span>rc8vk   <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">12</span>h
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h3 id="_3-3-在某目录下已存放包含上述产生数据的etcd快照" tabindex="-1"><a class="header-anchor" href="#_3-3-在某目录下已存放包含上述产生数据的etcd快照" aria-hidden="true">#</a> 3.3 在某目录下已存放包含上述产生数据的etcd快照</h3>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>ls
member  <span class="token keyword">snapshot</span><span class="token punctuation">.</span>db
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="_4-模拟数据的删除" tabindex="-1"><a class="header-anchor" href="#_4-模拟数据的删除" aria-hidden="true">#</a> 4 模拟数据的删除</h2>
<p>default和test namespace下pod都被干掉</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code>kubectl <span class="token keyword">get</span> pod
No <span class="token class-name">resources</span> found <span class="token keyword">in</span> <span class="token keyword">default</span> <span class="token keyword">namespace</span><span class="token punctuation">.</span>
<span class="token punctuation">[</span>root@node1 etcd<span class="token operator">-</span><span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19_02</span><span class="token punctuation">:</span><span class="token number">00</span><span class="token punctuation">:</span><span class="token number">01</span><span class="token punctuation">]</span># kubectl <span class="token keyword">get</span> pod <span class="token operator">-</span>n test
No <span class="token class-name">resources</span> found <span class="token keyword">in</span> test <span class="token keyword">namespace</span><span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h2 id="_5-数据的恢复" tabindex="-1"><a class="header-anchor" href="#_5-数据的恢复" aria-hidden="true">#</a> 5 数据的恢复</h2>
<h3 id="_5-1-准备工作" tabindex="-1"><a class="header-anchor" href="#_5-1-准备工作" aria-hidden="true">#</a> 5.1 准备工作</h3>
<p>停止所有master上kube-apiserver服务，因为和etcd交互是kube-apiserver。此步骤不会影响正常运行的pod。</p>
<h4 id="_5-1-1-所有master机器上操作如下指令-将kube-apiserver-yaml文件移除当前目录下-作用是停止kube-apiserver服务" tabindex="-1"><a class="header-anchor" href="#_5-1-1-所有master机器上操作如下指令-将kube-apiserver-yaml文件移除当前目录下-作用是停止kube-apiserver服务" aria-hidden="true">#</a> 5.1.1 所有master机器上操作如下指令,将kube-apiserver.yaml文件移除当前目录下，作用是停止kube-apiserver服务</h4>
<div class="language-undefined ext-undefined line-numbers-mode"><pre v-pre class="language-undefined"><code>mv /etc/kubernetes/manifests/kube-apiserver.yaml .
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="_5-1-2-检查kube-apiserver服务已停止" tabindex="-1"><a class="header-anchor" href="#_5-1-2-检查kube-apiserver服务已停止" aria-hidden="true">#</a> 5.1.2 检查kube-apiserver服务已停止</h4>
<div class="language-perl ext-perl line-numbers-mode"><pre v-pre class="language-perl"><code>kubectl get pod <span class="token operator">-</span>n kube<span class="token operator">-</span>system <span class="token operator">|</span> grep kube<span class="token operator">-</span>apiserver
Unable to connect to the server<span class="token punctuation">:</span> EOF
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h4 id="_5-1-3-所有etcd机器上-停止etcd运行-此步操作不会影响现有的pod-只是不能新建、删除pod。" tabindex="-1"><a class="header-anchor" href="#_5-1-3-所有etcd机器上-停止etcd运行-此步操作不会影响现有的pod-只是不能新建、删除pod。" aria-hidden="true">#</a> 5.1.3 所有etcd机器上，停止etcd运行，此步操作不会影响现有的pod，只是不能新建、删除pod。</h4>
<div class="language-vbnet ext-vbnet line-numbers-mode"><pre v-pre class="language-vbnet"><code>systemctl <span class="token keyword">stop</span> etcd
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="_5-1-4-查看etcd服务是否已停止" tabindex="-1"><a class="header-anchor" href="#_5-1-4-查看etcd服务是否已停止" aria-hidden="true">#</a> 5.1.4 查看etcd服务是否已停止</h4>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code>docker ps <span class="token operator">-</span>a <span class="token operator">|</span> grep etcd
<span class="token number">18d</span>fbbfb8317   kubesphere<span class="token operator">/</span>etcd<span class="token operator">:</span>v3<span class="token punctuation">.</span><span class="token number">3.12</span>            <span class="token string">"/usr/local/bin/etcd"</span>    <span class="token number">15</span> hours ago   <span class="token class-name">Exited</span> <span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span> <span class="token number">45</span> seconds ago             etcd3
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h4 id="_5-1-5-移除所有etcd存储目录下数据-不同环境下-存储目录可能不一样-可以通过systemctl-status-etcd查看etcd-配置参数。" tabindex="-1"><a class="header-anchor" href="#_5-1-5-移除所有etcd存储目录下数据-不同环境下-存储目录可能不一样-可以通过systemctl-status-etcd查看etcd-配置参数。" aria-hidden="true">#</a> 5.1.5 移除所有etcd存储目录下数据，不同环境下，存储目录可能不一样，可以通过systemctl status etcd查看etcd 配置参数。</h4>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code>mv <span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd <span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd<span class="token punctuation">.</span>bak
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="_5-1-6-将node1机器上的快照snapshot-db分别拷贝到另外两台etcd机器上。" tabindex="-1"><a class="header-anchor" href="#_5-1-6-将node1机器上的快照snapshot-db分别拷贝到另外两台etcd机器上。" aria-hidden="true">#</a> 5.1.6 将node1机器上的快照snapshot.db分别拷贝到另外两台etcd机器上。</h4>
<div class="language-ruby ext-rb line-numbers-mode"><pre v-pre class="language-ruby"><code>scp snapshot<span class="token punctuation">.</span>db <span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token operator">/</span>root


scp snapshot<span class="token punctuation">.</span>db <span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token operator">/</span>root
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="_5-2-恢复备份" tabindex="-1"><a class="header-anchor" href="#_5-2-恢复备份" aria-hidden="true">#</a> 5.2 恢复备份</h3>
<p>不同环境下，目录可能不一样，可以通过systemctl status etcd查看etcd 配置参数。特别需要注意name、initial-cluster、initial-cluster-token、initial-advertise-peer-urls和data-dir参数的值。</p>
<h4 id="_5-2-1-在第一台etcd节点上-注意需要etcdctl-api-3、name值、ip值、snapshot-db文件目录和data-dir目录。" tabindex="-1"><a class="header-anchor" href="#_5-2-1-在第一台etcd节点上-注意需要etcdctl-api-3、name值、ip值、snapshot-db文件目录和data-dir目录。" aria-hidden="true">#</a> 5.2.1 在第一台etcd节点上，注意需要ETCDCTL_API=3、name值、ip值、snapshot.db文件目录和data-dir目录。</h4>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token constant">ETCDCTL_API</span><span class="token operator">=</span><span class="token number">3</span> 
一条指令，可以直接在终端上修改里面参数
etcdctl snapshot restore snapshot<span class="token punctuation">.</span>db <span class="token operator">--</span>name etcd1 <span class="token operator">--</span>initial<span class="token operator">-</span>cluster <span class="token string">"etcd1=https://192.168.0.25:2380,etcd2=https://192.168.0.26:2380,etcd3=https://192.168.0.28:2380"</span> <span class="token operator">--</span>initial<span class="token operator">-</span>cluster<span class="token operator">-</span>token k8s_etcd <span class="token operator">--</span>initial<span class="token operator">-</span>advertise<span class="token operator">-</span>peer<span class="token operator">-</span>urls https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2380</span> <span class="token operator">--</span>data<span class="token operator">-</span>dir<span class="token operator">=</span><span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd
和上面指令一样作用，把长的指令以换行形式展现
etcdctl snapshot restore snapshot<span class="token punctuation">.</span>db <span class="token operator">--</span>name etcd1 \
<span class="token operator">--</span>initial<span class="token operator">-</span>cluster <span class="token string">"etcd1=https://192.168.0.25:2380,etcd2=https://192.168.0.26:2380,etcd3=https://192.168.0.28:2380"</span> \
<span class="token operator">--</span>initial<span class="token operator">-</span>cluster<span class="token operator">-</span>token k8s_etcd \
<span class="token operator">--</span>initial<span class="token operator">-</span>advertise<span class="token operator">-</span>peer<span class="token operator">-</span>urls https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2380</span> \
<span class="token operator">--</span>data<span class="token operator">-</span>dir<span class="token operator">=</span><span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd

<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">17</span><span class="token operator">:</span><span class="token number">06.773113</span> <span class="token constant">I</span> <span class="token operator">|</span> mvcc<span class="token operator">:</span> restore compact to <span class="token number">96139</span>
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">17</span><span class="token operator">:</span><span class="token number">06.800086</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 7370b1d3dc967c <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">17</span><span class="token operator">:</span><span class="token number">06.800159</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 2ef3cfc4ca48ad38 <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">17</span><span class="token operator">:</span><span class="token number">06.800190</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 3a0c86c4c744477c <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><h4 id="_5-2-2-第二台和第三台etcd恢复数据-同样需要改变etcdctl-api-3、name值、ip值、snapshot-db文件目录和data-dir目录。" tabindex="-1"><a class="header-anchor" href="#_5-2-2-第二台和第三台etcd恢复数据-同样需要改变etcdctl-api-3、name值、ip值、snapshot-db文件目录和data-dir目录。" aria-hidden="true">#</a> 5.2.2 第二台和第三台etcd恢复数据，同样需要改变ETCDCTL_API=3、name值、ip值、snapshot.db文件目录和data-dir目录。</h4>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token constant">ETCDCTL_API</span><span class="token operator">=</span><span class="token number">3</span>
一条指令，可以直接在终端上修改里面参数
etcdctl snapshot restore snapshot<span class="token punctuation">.</span>db <span class="token operator">--</span>name etcd2 <span class="token operator">--</span>initial<span class="token operator">-</span>cluster <span class="token string">"etcd1=https://192.168.0.25:2380,etcd2=https://192.168.0.26:2380,etcd3=https://192.168.0.28:2380"</span> <span class="token operator">--</span>initial<span class="token operator">-</span>cluster<span class="token operator">-</span>token k8s_etcd <span class="token operator">--</span>initial<span class="token operator">-</span>advertise<span class="token operator">-</span>peer<span class="token operator">-</span>urls https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2380</span> <span class="token operator">--</span>data<span class="token operator">-</span>dir<span class="token operator">=</span><span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd
和上面指令一样作用，把长的指令以换行形式展现
etcdctl snapshot restore snapshot<span class="token punctuation">.</span>db <span class="token operator">--</span>name etcd2 \
<span class="token operator">--</span>initial<span class="token operator">-</span>cluster <span class="token string">"etcd1=https://192.168.0.25:2380,etcd2=https://192.168.0.26:2380,etcd3=https://192.168.0.28:2380"</span> \
<span class="token operator">--</span>initial<span class="token operator">-</span>cluster<span class="token operator">-</span>token k8s_etcd \
<span class="token operator">--</span>initial<span class="token operator">-</span>advertise<span class="token operator">-</span>peer<span class="token operator">-</span>urls https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2380</span> \
<span class="token operator">--</span>data<span class="token operator">-</span>dir<span class="token operator">=</span><span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd

<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">19</span><span class="token operator">:</span><span class="token number">59.857363</span> <span class="token constant">I</span> <span class="token operator">|</span> mvcc<span class="token operator">:</span> restore compact to <span class="token number">96139</span>
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">19</span><span class="token operator">:</span><span class="token number">59.873793</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 7370b1d3dc967c <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">19</span><span class="token operator">:</span><span class="token number">59.873837</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 2ef3cfc4ca48ad38 <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">19</span><span class="token operator">:</span><span class="token number">59.873852</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 3a0c86c4c744477c <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71

<span class="token keyword">export</span> <span class="token constant">ETCDCTL_API</span><span class="token operator">=</span><span class="token number">3</span>
一条指令，可以直接在终端上修改里面参数
etcdctl snapshot restore snapshot<span class="token punctuation">.</span>db <span class="token operator">--</span>name etcd3 <span class="token operator">--</span>initial<span class="token operator">-</span>cluster <span class="token string">"etcd1=https://192.168.0.25:2380,etcd2=https://192.168.0.26:2380,etcd3=https://192.168.0.28:2380"</span> <span class="token operator">--</span>initial<span class="token operator">-</span>cluster<span class="token operator">-</span>token k8s_etcd <span class="token operator">--</span>initial<span class="token operator">-</span>advertise<span class="token operator">-</span>peer<span class="token operator">-</span>urls https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2380</span> <span class="token operator">--</span>data<span class="token operator">-</span>dir<span class="token operator">=</span><span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd
和上面指令一样作用，把长的指令以换行形式展现
etcdctl snapshot restore snapshot<span class="token punctuation">.</span>db <span class="token operator">--</span>name etcd3 \
<span class="token operator">--</span>initial<span class="token operator">-</span>cluster <span class="token string">"etcd1=https://192.168.0.25:2380,etcd2=https://192.168.0.26:2380,etcd3=https://192.168.0.28:2380"</span> \
<span class="token operator">--</span>initial<span class="token operator">-</span>cluster<span class="token operator">-</span>token k8s_etcd \
<span class="token operator">--</span>initial<span class="token operator">-</span>advertise<span class="token operator">-</span>peer<span class="token operator">-</span>urls https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2380</span> \
<span class="token operator">--</span>data<span class="token operator">-</span>dir<span class="token operator">=</span><span class="token operator">/</span><span class="token keyword">var</span><span class="token operator">/</span>lib<span class="token operator">/</span>etcd

<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">22</span><span class="token operator">:</span><span class="token number">21.423215</span> <span class="token constant">I</span> <span class="token operator">|</span> mvcc<span class="token operator">:</span> restore compact to <span class="token number">96139</span>
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">22</span><span class="token operator">:</span><span class="token number">21.438319</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 7370b1d3dc967c <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">22</span><span class="token operator">:</span><span class="token number">21.438357</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 2ef3cfc4ca48ad38 <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
<span class="token number">2021</span><span class="token operator">-</span><span class="token number">01</span><span class="token operator">-</span><span class="token number">19</span> <span class="token number">11</span><span class="token operator">:</span><span class="token number">22</span><span class="token operator">:</span><span class="token number">21.438371</span> <span class="token constant">I</span> <span class="token operator">|</span> etcdserver<span class="token operator">/</span>membership<span class="token operator">:</span> added member 3a0c86c4c744477c <span class="token punctuation">[</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2380</span><span class="token punctuation">]</span> to cluster e4d7f96e88cc9d71
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br></div></div><h4 id="_5-2-3-上面三台etcd启动" tabindex="-1"><a class="header-anchor" href="#_5-2-3-上面三台etcd启动" aria-hidden="true">#</a> 5.2.3 上面三台etcd启动</h4>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>systemctl <span class="token keyword">start</span> etcd
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="_5-2-4-检查etcd集群状态-注意-如果有证书-需要加上证书-在哪台etcd机器执行-注意找到对应的证书文件及最后面加endpoint-health字样。" tabindex="-1"><a class="header-anchor" href="#_5-2-4-检查etcd集群状态-注意-如果有证书-需要加上证书-在哪台etcd机器执行-注意找到对应的证书文件及最后面加endpoint-health字样。" aria-hidden="true">#</a> 5.2.4 检查etcd集群状态，注意：如果有证书，需要加上证书；在哪台etcd机器执行，注意找到对应的证书文件及最后面加endpoint health字样。</h4>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>一条指令，可以直接在终端上修改里面参数
etcdctl <span class="token operator">--</span>cacert<span class="token operator">=</span><span class="token operator">/</span>etc<span class="token operator">/</span>ssl<span class="token operator">/</span>etcd<span class="token operator">/</span>ssl<span class="token operator">/</span>ca<span class="token punctuation">.</span>pem <span class="token operator">--</span>cert<span class="token operator">=</span><span class="token operator">/</span>etc<span class="token operator">/</span>ssl<span class="token operator">/</span>etcd<span class="token operator">/</span>ssl<span class="token operator">/</span>node<span class="token operator">-</span>node3<span class="token punctuation">.</span>pem <span class="token operator">--</span>key<span class="token operator">=</span><span class="token operator">/</span>etc<span class="token operator">/</span>ssl<span class="token operator">/</span>etcd<span class="token operator">/</span>ssl<span class="token operator">/</span>node<span class="token operator">-</span>node3<span class="token operator">-</span>key<span class="token punctuation">.</span>pem <span class="token operator">--</span>endpoints<span class="token operator">=</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2379</span><span class="token punctuation">,</span><span class="token literal-property property">https</span><span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2379</span><span class="token punctuation">,</span><span class="token literal-property property">https</span><span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2379</span> endpoint health
和上面指令一样作用，把长的指令以换行形式展现
etcdctl <span class="token operator">--</span>cacert<span class="token operator">=</span><span class="token operator">/</span>etc<span class="token operator">/</span>ssl<span class="token operator">/</span>etcd<span class="token operator">/</span>ssl<span class="token operator">/</span>ca<span class="token punctuation">.</span>pem \
<span class="token operator">--</span>cert<span class="token operator">=</span><span class="token operator">/</span>etc<span class="token operator">/</span>ssl<span class="token operator">/</span>etcd<span class="token operator">/</span>ssl<span class="token operator">/</span>node<span class="token operator">-</span>node3<span class="token punctuation">.</span>pem \
<span class="token operator">--</span>key<span class="token operator">=</span><span class="token operator">/</span>etc<span class="token operator">/</span>ssl<span class="token operator">/</span>etcd<span class="token operator">/</span>ssl<span class="token operator">/</span>node<span class="token operator">-</span>node3<span class="token operator">-</span>key<span class="token punctuation">.</span>pem \
<span class="token operator">--</span>endpoints<span class="token operator">=</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2379</span><span class="token punctuation">,</span><span class="token literal-property property">https</span><span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2379</span><span class="token punctuation">,</span><span class="token literal-property property">https</span><span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2379</span> \
endpoint health

<span class="token literal-property property">https</span><span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.28</span><span class="token operator">:</span><span class="token number">2379</span> is healthy<span class="token operator">:</span> successfully committed proposal<span class="token operator">:</span> took <span class="token operator">=</span> <span class="token number">11</span><span class="token punctuation">.</span>664519ms
<span class="token literal-property property">https</span><span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.26</span><span class="token operator">:</span><span class="token number">2379</span> is healthy<span class="token operator">:</span> successfully committed proposal<span class="token operator">:</span> took <span class="token operator">=</span> <span class="token number">5</span><span class="token punctuation">.</span>04665ms
<span class="token literal-property property">https</span><span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">192.168</span><span class="token number">.0</span><span class="token number">.25</span><span class="token operator">:</span><span class="token number">2379</span> is healthy<span class="token operator">:</span> successfully committed proposal<span class="token operator">:</span> took <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">.</span>837265ms
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h4 id="_5-2-5-三台etcd全部正常-分别到每台master启动kube-apiserver" tabindex="-1"><a class="header-anchor" href="#_5-2-5-三台etcd全部正常-分别到每台master启动kube-apiserver" aria-hidden="true">#</a> 5.2.5 三台etcd全部正常，分别到每台master启动kube-apiserver</h4>
<div class="language-undefined ext-undefined line-numbers-mode"><pre v-pre class="language-undefined"><code>mv /root/kube-apiserver.yaml /etc/kubernetes/manifests/
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h4 id="_5-2-6-检查kubernetes集群和创建的pod是否恢复正常-包括etcd服务、kube-apiserver服务及对应ns下删除的pod。" tabindex="-1"><a class="header-anchor" href="#_5-2-6-检查kubernetes集群和创建的pod是否恢复正常-包括etcd服务、kube-apiserver服务及对应ns下删除的pod。" aria-hidden="true">#</a> 5.2.6 检查kubernetes集群和创建的pod是否恢复正常，包括etcd服务、kube-apiserver服务及对应ns下删除的pod。</h4>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>kubectl get pod <span class="token operator">-</span>n kube<span class="token operator">-</span>system <span class="token operator">|</span> grep kube<span class="token operator">-</span>apiserver
kube<span class="token operator">-</span>apiserver<span class="token operator">-</span>node1                           <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">16</span>h
kube<span class="token operator">-</span>apiserver<span class="token operator">-</span>node2                           <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">16</span>h
kube<span class="token operator">-</span>apiserver<span class="token operator">-</span>node3                           <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">16</span>h
<span class="token punctuation">[</span>root<span class="token variable">@node1</span> ssl<span class="token punctuation">]</span><span class="token comment"># docker ps -a | grep etcd</span>
<span class="token number">156</span>b19a72bf0   kubesphere<span class="token operator">/</span>etcd:v3<span class="token punctuation">.</span><span class="token number">3.12</span>      <span class="token string">"/usr/local/bin/etcd"</span>    <span class="token number">15</span> minutes ago   Up <span class="token number">15</span> minutes                           etcd1


kubectl get pod
NAME                      READY   <span class="token keyword">STATUS</span>              RESTARTS   AGE
nginx<span class="token operator">-</span><span class="token number">6</span>db489d4b7<span class="token operator">-</span>jdfkw    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running             <span class="token number">0</span>          <span class="token number">13</span>h
nginx1<span class="token operator">-</span><span class="token number">675</span>bf6c9f<span class="token operator">-</span>jndrx    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running             <span class="token number">0</span>          <span class="token number">13</span>h
nginx2<span class="token operator">-</span><span class="token number">6</span>dfc958b55<span class="token operator">-</span>vgsc4   <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running             <span class="token number">0</span>          <span class="token number">13</span>h
nginx3<span class="token operator">-</span><span class="token number">8</span>f65b44f9<span class="token operator">-</span><span class="token number">2</span>pk4l    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running             <span class="token number">0</span>          <span class="token number">13</span>h
nginx4<span class="token operator">-</span><span class="token number">9</span>bb966479<span class="token operator">-</span>svhs6    <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running             <span class="token number">0</span>          <span class="token number">13</span>h
nginx5<span class="token operator">-</span><span class="token number">7</span>d4d998c6c<span class="token operator">-</span><span class="token number">7</span>xlp8   <span class="token number">0</span><span class="token operator">/</span><span class="token number">1</span>     ContainerCreating   <span class="token number">0</span>          <span class="token number">13</span>h
nginx6<span class="token operator">-</span><span class="token number">79444687</span>cf<span class="token operator">-</span>rc8vk   <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running             <span class="token number">0</span>          <span class="token number">13</span>h
<span class="token punctuation">[</span>root<span class="token variable">@node1</span> ssl<span class="token punctuation">]</span><span class="token comment"># kubectl get pod -n test</span>
NAME                              READY   <span class="token keyword">STATUS</span>    RESTARTS   AGE
details<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">7</span>d78fc5688<span class="token operator">-</span>ntvtd       <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">13</span>h
productpage<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">844495</span>cb4b<span class="token operator">-</span>qn6l9   <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">13</span>h
ratings<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">55</span>ccf46fb4<span class="token operator">-</span>pwqw7       <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">13</span>h
reviews<span class="token operator">-</span>v1<span class="token operator">-</span><span class="token number">68</span>bb7b8c4f<span class="token operator">-</span>h6vr9       <span class="token number">1</span><span class="token operator">/</span><span class="token number">1</span>     Running   <span class="token number">0</span>          <span class="token number">13</span>h
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br></div></div><h2 id="_6-总结" tabindex="-1"><a class="header-anchor" href="#_6-总结" aria-hidden="true">#</a> 6 总结</h2>
<p>Kubernetes 集群备份主要是备份etcd集群。而恢复时，主要考虑恢复整个顺序：</p>
<p>停止Kube-apiserver–&gt; 停止etcd–&gt; 恢复数据–&gt;启动etcd–&gt;启动kube-apiserver</p>
<p>注意：备份etcd集群时，只需要备份一个etcd就行，恢复时，拿同一份备份数据恢复。</p>
</template>
