<template><h1 id="附录-f-i-o-与-i-o-重定向详细介绍" tabindex="-1"><a class="header-anchor" href="#附录-f-i-o-与-i-o-重定向详细介绍" aria-hidden="true">#</a> 附录 F. I/O 与 I/O 重定向详细介绍</h1>
<p>一个指令会预期前三个文件描述符可用。第一个， <em>fd 0</em> (标准输入， <code>stdin</code>) 用于读取。其他两个 (<em>fd 1</em>, <code>stdout</code> 和 <em>fd 2</em>, <code>stderr</code>) 用于写入。</p>
<p>每个指令都关联着一个 <code>stdin</code>, <code>stdout</code> 和 <code>stderr</code> 。<strong><code>ls 2&gt;&amp;1</code></strong> 意味着临时将 ls 的 <code>stderr</code> 连接到与 Shell 的 <code>stdout</code> 一样的「资源」。</p>
<p>按照惯例，指令从 fd 0 (<code>stdin</code>) 读取输入，正常输出打印到 fd 1 (<code>stdin</code>)，错误输出打印到 fd 2 (<code>stderr</code>)。如果这三个文件描述符有一个没被打开，你可能会碰上问题：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>bash$ <span class="token function">cat</span> /etc/passwd <span class="token operator">>&amp;</span>-
cat: standard output: Bad <span class="token function">file</span> descriptor
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>例如，当 <strong>xterm</strong> 运行，它首先自我初始化。在运行用户的 Shell 之前， <strong>xterm</strong> 会打开终端设备 (/dev/pts/<n> 或类似) 三次。</p>
<p>此时 Bash 继承这三个文件描述符，且每个 Bash 运行的指令 (子进程) 因此继承它们，除非你重定向它们。重定向意味着重设一个文件描述符到另一个文件 (或者管道，或任何有权限的东西)。文件描述符可以本地重设 (对于一个指令、指令组、子 Shell、while / case / for 循环等)，或者，对余下的 Shell 会话全局重设 (通过 exec)。</p>
<p><code>ls &gt; /dev/null</code> 意味着在其文件描述符 1 连接到 <code>/dev/null</code> 的情况下运行 <strong>ls</strong> 。</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>bash$ <span class="token function">lsof</span> -a -p <span class="token variable">$$</span> -d0,1,2
COMMAND PID     <span class="token environment constant">USER</span>   FD   TYPE DEVICE SIZE NODE NAME
 <span class="token function">bash</span>    <span class="token number">363</span> bozo        0u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1
 <span class="token function">bash</span>    <span class="token number">363</span> bozo        1u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1
 <span class="token function">bash</span>    <span class="token number">363</span> bozo        2u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1


bash$ <span class="token builtin class-name">exec</span> <span class="token operator"><span class="token file-descriptor important">2</span>></span> /dev/null
bash$ <span class="token function">lsof</span> -a -p <span class="token variable">$$</span> -d0,1,2
COMMAND PID     <span class="token environment constant">USER</span>   FD   TYPE DEVICE SIZE NODE NAME
 <span class="token function">bash</span>    <span class="token number">371</span> bozo        0u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1
 <span class="token function">bash</span>    <span class="token number">371</span> bozo        1u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1
 <span class="token function">bash</span>    <span class="token number">371</span> bozo        2w   CHR    <span class="token number">1,3</span>       <span class="token number">120</span> /dev/null


bash$ <span class="token function">bash</span> -c <span class="token string">'lsof -a -p $$ -d0,1,2'</span> <span class="token operator">|</span> <span class="token function">cat</span>
COMMAND PID <span class="token environment constant">USER</span>   FD   TYPE DEVICE SIZE NODE NAME
 <span class="token function">lsof</span>    <span class="token number">379</span> root    0u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1
 <span class="token function">lsof</span>    <span class="token number">379</span> root    1w  FIFO    <span class="token number">0,0</span>      <span class="token number">7118</span> pipe
 <span class="token function">lsof</span>    <span class="token number">379</span> root    2u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1


bash$ <span class="token builtin class-name">echo</span> <span class="token string">"<span class="token variable"><span class="token variable">$(</span><span class="token function">bash</span> -c <span class="token string">'lsof -a -p $$ -d0,1,2'</span> <span class="token operator"><span class="token file-descriptor important">2</span>></span><span class="token file-descriptor important">&amp;1</span><span class="token variable">)</span></span>"</span>
COMMAND PID <span class="token environment constant">USER</span>   FD   TYPE DEVICE SIZE NODE NAME
 <span class="token function">lsof</span>    <span class="token number">426</span> root    0u   CHR  <span class="token number">136,1</span>         <span class="token number">3</span> /dev/pts/1
 <span class="token function">lsof</span>    <span class="token number">426</span> root    1w  FIFO    <span class="token number">0,0</span>      <span class="token number">7520</span> pipe
 <span class="token function">lsof</span>    <span class="token number">426</span> root    2w  FIFO    <span class="token number">0,0</span>      <span class="token number">7520</span> pipe
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br></div></div><h2 id="练习" tabindex="-1"><a class="header-anchor" href="#练习" aria-hidden="true">#</a> 练习</h2>
<p>分析以下脚本。</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token shebang important">#! /usr/bin/env bash</span>

<span class="token function">mkfifo</span> /tmp/fifo1 /tmp/fifo2
<span class="token keyword">while</span> <span class="token builtin class-name">read</span> a<span class="token punctuation">;</span> <span class="token keyword">do</span> <span class="token builtin class-name">echo</span> <span class="token string">"FIFO1: <span class="token variable">$a</span>"</span><span class="token punctuation">;</span> <span class="token keyword">done</span> <span class="token operator">&lt;</span> /tmp/fifo1 <span class="token operator">&amp;</span> <span class="token builtin class-name">exec</span> <span class="token operator"><span class="token file-descriptor important">7</span>></span> /tmp/fifo1
<span class="token builtin class-name">exec</span> <span class="token operator"><span class="token file-descriptor important">8</span>></span> <span class="token operator">></span><span class="token punctuation">(</span><span class="token keyword">while</span> <span class="token builtin class-name">read</span> a<span class="token punctuation">;</span> <span class="token keyword">do</span> <span class="token builtin class-name">echo</span> <span class="token string">"FD8: <span class="token variable">$a</span>, to fd7"</span><span class="token punctuation">;</span> <span class="token keyword">done</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;7</span><span class="token punctuation">)</span>

<span class="token builtin class-name">exec</span> <span class="token operator"><span class="token file-descriptor important">3</span>></span><span class="token file-descriptor important">&amp;1</span>
<span class="token punctuation">(</span>
 <span class="token punctuation">(</span>
  <span class="token punctuation">(</span>
   <span class="token keyword">while</span> <span class="token builtin class-name">read</span> a<span class="token punctuation">;</span> <span class="token keyword">do</span> <span class="token builtin class-name">echo</span> <span class="token string">"FIFO2: <span class="token variable">$a</span>"</span><span class="token punctuation">;</span> <span class="token keyword">done</span> <span class="token operator">&lt;</span> /tmp/fifo2 <span class="token operator">|</span> <span class="token function">tee</span> /dev/stderr <span class="token punctuation">\</span>
   <span class="token operator">|</span> <span class="token function">tee</span> /dev/fd/4 <span class="token operator">|</span> <span class="token function">tee</span> /dev/fd/5 <span class="token operator">|</span> <span class="token function">tee</span> /dev/fd/6 <span class="token operator">></span><span class="token file-descriptor important">&amp;7</span> <span class="token operator">&amp;</span> <span class="token builtin class-name">exec</span> <span class="token operator"><span class="token file-descriptor important">3</span>></span> /tmp/fifo2

   <span class="token builtin class-name">echo</span> 1st, to stdout
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 2nd, to stderr <span class="token operator">></span><span class="token file-descriptor important">&amp;2</span>
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 3rd, to fd <span class="token number">3</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;3</span>
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 4th, to fd <span class="token number">4</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;4</span>
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 5th, to fd <span class="token number">5</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;5</span>
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 6th, through a pipe <span class="token operator">|</span> <span class="token function">sed</span> <span class="token string">'s/.*/PIPE: &amp;, to fd 5/'</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;5</span>
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 7th, to fd <span class="token number">6</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;6</span>
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 8th, to fd <span class="token number">7</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;7</span>
   <span class="token function">sleep</span> <span class="token number">1</span>
   <span class="token builtin class-name">echo</span> 9th, to fd <span class="token number">8</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;8</span>

  <span class="token punctuation">)</span> <span class="token operator"><span class="token file-descriptor important">4</span>></span><span class="token file-descriptor important">&amp;1</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;3</span> <span class="token operator"><span class="token file-descriptor important">3</span>>&amp;</span>- <span class="token operator">|</span> <span class="token keyword">while</span> <span class="token builtin class-name">read</span> a<span class="token punctuation">;</span> <span class="token keyword">do</span> <span class="token builtin class-name">echo</span> <span class="token string">"FD4: <span class="token variable">$a</span>"</span><span class="token punctuation">;</span> <span class="token keyword">done</span> <span class="token operator"><span class="token file-descriptor important">1</span>></span><span class="token file-descriptor important">&amp;3</span> <span class="token operator"><span class="token file-descriptor important">5</span>>&amp;</span>- <span class="token operator"><span class="token file-descriptor important">6</span>>&amp;</span>-
 <span class="token punctuation">)</span> <span class="token operator"><span class="token file-descriptor important">5</span>></span><span class="token file-descriptor important">&amp;1</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;3</span> <span class="token operator">|</span> <span class="token keyword">while</span> <span class="token builtin class-name">read</span> a<span class="token punctuation">;</span> <span class="token keyword">do</span> <span class="token builtin class-name">echo</span> <span class="token string">"FD5: <span class="token variable">$a</span>"</span><span class="token punctuation">;</span> <span class="token keyword">done</span> <span class="token operator"><span class="token file-descriptor important">1</span>></span><span class="token file-descriptor important">&amp;3</span> <span class="token operator"><span class="token file-descriptor important">6</span>>&amp;</span>-
<span class="token punctuation">)</span> <span class="token operator"><span class="token file-descriptor important">6</span>></span><span class="token file-descriptor important">&amp;1</span> <span class="token operator">></span><span class="token file-descriptor important">&amp;3</span> <span class="token operator">|</span> <span class="token keyword">while</span> <span class="token builtin class-name">read</span> a<span class="token punctuation">;</span> <span class="token keyword">do</span> <span class="token builtin class-name">echo</span> <span class="token string">"FD6: <span class="token variable">$a</span>"</span><span class="token punctuation">;</span> <span class="token keyword">done</span> <span class="token operator"><span class="token file-descriptor important">3</span>>&amp;</span>-

<span class="token function">rm</span> -f /tmp/fifo1 /tmp/fifo2


<span class="token comment"># 对每个指令和子 Shell，猜猜哪个 fd 指向什么。</span>
<span class="token comment"># 祝你好运！</span>

<span class="token builtin class-name">exit</span> <span class="token number">0</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br></div></div></template>
