<template><div><h1 id="附录-t-ascii-表" tabindex="-1"><a class="header-anchor" href="#附录-t-ascii-表" aria-hidden="true">#</a> 附录 T. ASCII 表</h1>
<p>传统上，这类书的附录会有一个 ASCII 表。但本书不会。取而代之的是这些生成一张完整 ASCII 表的简短脚本。</p>
<p>例 T-1. 一个生成 ASCII 表的脚本</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token shebang important">#!/bin/bash</span>
<span class="token comment"># ascii.sh</span>
<span class="token comment"># ver. 0.2, reldate 26 Aug 2008</span>
<span class="token comment"># Patched by ABS Guide author.</span>

<span class="token comment"># Original script by Sebastian Arming.</span>
<span class="token comment"># Used with permission (thanks!).</span>

<span class="token builtin class-name">exec</span> <span class="token operator">></span>ASCII.txt         <span class="token comment">#  Save stdout to file,</span>
                        <span class="token comment">#+ as in the example scripts</span>
                        <span class="token comment">#+ reassign-stdout.sh and upperconv.sh.</span>

<span class="token assign-left variable">MAXNUM</span><span class="token operator">=</span><span class="token number">256</span>
<span class="token assign-left variable"><span class="token environment constant">COLUMNS</span></span><span class="token operator">=</span><span class="token number">5</span>
<span class="token assign-left variable">OCT</span><span class="token operator">=</span><span class="token number">8</span>
<span class="token assign-left variable">OCTSQU</span><span class="token operator">=</span><span class="token number">64</span>
<span class="token assign-left variable">LITTLESPACE</span><span class="token operator">=</span>-3
<span class="token assign-left variable">BIGSPACE</span><span class="token operator">=</span>-5

<span class="token assign-left variable">i</span><span class="token operator">=</span><span class="token number">1</span> <span class="token comment"># Decimal counter</span>
<span class="token assign-left variable">o</span><span class="token operator">=</span><span class="token number">1</span> <span class="token comment"># Octal counter</span>

<span class="token keyword">while</span> <span class="token punctuation">[</span> <span class="token string">"<span class="token variable">$i</span>"</span> <span class="token parameter variable">-lt</span> <span class="token string">"<span class="token variable">$MAXNUM</span>"</span> <span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token keyword">do</span>  <span class="token comment"># We don't have to count past 400 octal.</span>
        <span class="token assign-left variable">paddi</span><span class="token operator">=</span><span class="token string">"    <span class="token variable">$i</span>"</span>
        <span class="token builtin class-name">echo</span> <span class="token parameter variable">-n</span> <span class="token string">"<span class="token variable">${paddi<span class="token operator">:</span> $BIGSPACE}</span>  "</span>       <span class="token comment"># Column spacing.</span>
        <span class="token assign-left variable">paddo</span><span class="token operator">=</span><span class="token string">"00<span class="token variable">$o</span>"</span>
<span class="token comment">#       echo -ne "\\${paddo: $LITTLESPACE}"   # Original.</span>
        <span class="token builtin class-name">echo</span> <span class="token parameter variable">-ne</span> <span class="token string">"<span class="token entity" title="\\">\\</span>0<span class="token variable">${paddo<span class="token operator">:</span> $LITTLESPACE}</span>"</span>  <span class="token comment"># Fixup.</span>
<span class="token comment">#                   ^</span>
        <span class="token builtin class-name">echo</span> <span class="token parameter variable">-n</span> <span class="token string">"     "</span>
        <span class="token keyword">if</span> <span class="token variable"><span class="token punctuation">((</span> i <span class="token operator">%</span> $COLUMNS <span class="token operator">==</span> <span class="token number">0</span><span class="token punctuation">))</span></span><span class="token punctuation">;</span> <span class="token keyword">then</span>       <span class="token comment"># New line.</span>
           <span class="token builtin class-name">echo</span>
        <span class="token keyword">fi</span>
        <span class="token variable"><span class="token punctuation">((</span>i<span class="token operator">++</span><span class="token punctuation">,</span> o<span class="token operator">++</span><span class="token punctuation">))</span></span>
        <span class="token comment"># The octal notation for 8 is 10, and 64 decimal is 100 octal.</span>
        <span class="token variable"><span class="token punctuation">((</span> i <span class="token operator">%</span> $OCT <span class="token operator">==</span> <span class="token number">0</span><span class="token punctuation">))</span></span>    <span class="token operator">&amp;&amp;</span> <span class="token variable"><span class="token punctuation">((</span>o<span class="token operator">+=</span><span class="token number">2</span><span class="token punctuation">))</span></span>
        <span class="token variable"><span class="token punctuation">((</span> i <span class="token operator">%</span> $OCTSQU <span class="token operator">==</span> <span class="token number">0</span><span class="token punctuation">))</span></span> <span class="token operator">&amp;&amp;</span> <span class="token variable"><span class="token punctuation">((</span>o<span class="token operator">+=</span><span class="token number">20</span><span class="token punctuation">))</span></span>
<span class="token keyword">done</span>

<span class="token builtin class-name">exit</span> <span class="token variable">$?</span>

<span class="token comment"># Compare this script with the "pr-asc.sh" example.</span>
<span class="token comment"># This one handles "unprintable" characters.</span>

<span class="token comment"># Exercise:</span>
<span class="token comment"># Rewrite this script to use decimal numbers, rather than octal.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>例 T-2. 另一个 ASCII 表脚本</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token shebang important">#!/bin/bash</span>
<span class="token comment"># Script author: Joseph Steinhauser</span>
<span class="token comment"># Lightly edited by ABS Guide author, but not commented.</span>
<span class="token comment"># Used in ABS Guide with permission.</span>

<span class="token comment">#-------------------------------------------------------------------------</span>
<span class="token comment">#-- File:  ascii.sh    Print ASCII chart, base 10/8/16         (JETS-2012)</span>
<span class="token comment">#-------------------------------------------------------------------------</span>
<span class="token comment">#-- Usage: ascii [oct|dec|hex|help|8|10|16]</span>
<span class="token comment">#--</span>
<span class="token comment">#-- This script prints out a summary of ASCII char codes from Zero to 127.</span>
<span class="token comment">#-- Numeric values may be printed in Base10, Octal, or Hex.</span>
<span class="token comment">#--</span>
<span class="token comment">#-- Format Based on: /usr/share/lib/pub/ascii with base-10 as default.</span>
<span class="token comment">#-- For more detail, man ascii . . .</span>
<span class="token comment">#-------------------------------------------------------------------------</span>

<span class="token punctuation">[</span> <span class="token parameter variable">-n</span> <span class="token string">"<span class="token environment constant">$BASH_VERSION</span>"</span> <span class="token punctuation">]</span> <span class="token operator">&amp;&amp;</span> <span class="token builtin class-name">shopt</span> <span class="token parameter variable">-s</span> extglob

<span class="token keyword">case</span> <span class="token string">"<span class="token variable">$1</span>"</span> <span class="token keyword">in</span>
   oct<span class="token operator">|</span><span class="token punctuation">[</span>Oo<span class="token punctuation">]</span>?<span class="token punctuation">(</span><span class="token punctuation">[</span>Cc<span class="token punctuation">]</span><span class="token punctuation">[</span>Tt<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">|</span><span class="token number">8</span><span class="token punctuation">)</span>       <span class="token assign-left variable">Obase</span><span class="token operator">=</span>Octal<span class="token punctuation">;</span>  <span class="token assign-left variable">Numy</span><span class="token operator">=</span>3o<span class="token punctuation">;</span><span class="token punctuation">;</span>
   hex<span class="token operator">|</span><span class="token punctuation">[</span>Hh<span class="token punctuation">]</span>?<span class="token punctuation">(</span><span class="token punctuation">[</span>Ee<span class="token punctuation">]</span><span class="token punctuation">[</span>Xx<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">|</span><span class="token number">16</span><span class="token operator">|</span><span class="token punctuation">[</span>Xx<span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token assign-left variable">Obase</span><span class="token operator">=</span>Hex<span class="token punctuation">;</span>    <span class="token assign-left variable">Numy</span><span class="token operator">=</span>2X<span class="token punctuation">;</span><span class="token punctuation">;</span>
   <span class="token builtin class-name">help</span><span class="token operator">|</span>?<span class="token punctuation">(</span>-<span class="token punctuation">)</span><span class="token punctuation">[</span>h?<span class="token punctuation">]</span><span class="token punctuation">)</span>        <span class="token function">sed</span> <span class="token parameter variable">-n</span> <span class="token string">'2,/^[ ]*$/p'</span> <span class="token variable">$0</span><span class="token punctuation">;</span><span class="token builtin class-name">exit</span><span class="token punctuation">;</span><span class="token punctuation">;</span>
   code<span class="token operator">|</span><span class="token punctuation">[</span>Cc<span class="token punctuation">]</span><span class="token punctuation">[</span>Oo<span class="token punctuation">]</span><span class="token punctuation">[</span>Dd<span class="token punctuation">]</span><span class="token punctuation">[</span>Ee<span class="token punctuation">]</span><span class="token punctuation">)</span>sed <span class="token parameter variable">-n</span> <span class="token string">'/case/,$p'</span>   <span class="token variable">$0</span><span class="token punctuation">;</span><span class="token builtin class-name">exit</span><span class="token punctuation">;</span><span class="token punctuation">;</span>
   *<span class="token punctuation">)</span> <span class="token assign-left variable">Obase</span><span class="token operator">=</span>Decimal
<span class="token keyword">esac</span> <span class="token comment"># CODE is actually shorter than the chart!</span>

<span class="token builtin class-name">printf</span> <span class="token string">"<span class="token entity" title="\t">\t</span><span class="token entity" title="\t">\t</span>## <span class="token variable">$Obase</span> ASCII Chart ##<span class="token entity" title="\n">\n</span><span class="token entity" title="\n">\n</span>"</span><span class="token punctuation">;</span> <span class="token assign-left variable">FM1</span><span class="token operator">=</span><span class="token string">"|%0<span class="token variable">${Numy<span class="token operator">:-</span>3d}</span>"</span><span class="token punctuation">;</span> <span class="token assign-left variable">LD</span><span class="token operator">=</span>-1

<span class="token assign-left variable">AB</span><span class="token operator">=</span><span class="token string">"nul soh stx etx eot enq ack bel bs tab nl vt np cr so si dle"</span>
<span class="token assign-left variable">AD</span><span class="token operator">=</span><span class="token string">"dc1 dc2 dc3 dc4 nak syn etb can em sub esc fs gs rs us sp"</span>

<span class="token keyword">for</span> <span class="token for-or-select variable">TOK</span> <span class="token keyword">in</span> <span class="token variable">$AB</span> <span class="token variable">$AD</span><span class="token punctuation">;</span> <span class="token keyword">do</span> ABR<span class="token punctuation">[</span><span class="token variable"><span class="token variable">$((</span>LD<span class="token operator">+=</span><span class="token number">1</span><span class="token variable">))</span></span><span class="token punctuation">]</span><span class="token operator">=</span><span class="token variable">$TOK</span><span class="token punctuation">;</span> <span class="token keyword">done</span><span class="token punctuation">;</span>
ABR<span class="token punctuation">[</span><span class="token number">127</span><span class="token punctuation">]</span><span class="token operator">=</span>del

<span class="token assign-left variable">IDX</span><span class="token operator">=</span><span class="token number">0</span>
<span class="token keyword">while</span> <span class="token punctuation">[</span> <span class="token variable">$IDX</span> <span class="token parameter variable">-le</span> <span class="token number">127</span> <span class="token punctuation">]</span> <span class="token operator">&amp;&amp;</span> <span class="token assign-left variable">CHR</span><span class="token operator">=</span><span class="token string">"<span class="token variable">${ABR<span class="token punctuation">[</span>$IDX<span class="token punctuation">]</span>}</span>"</span>
   <span class="token keyword">do</span> <span class="token variable"><span class="token punctuation">((</span>${#CHR}<span class="token punctuation">))</span></span><span class="token operator">&amp;&amp;</span> <span class="token assign-left variable">FM2</span><span class="token operator">=</span><span class="token string">'%-3s'</span><span class="token operator">||</span> <span class="token assign-left variable">FM2</span><span class="token operator">=</span><span class="token variable"><span class="token variable">`</span><span class="token builtin class-name">printf</span> <span class="token string">'\\\\%o  '</span> $IDX<span class="token variable">`</span></span>
      <span class="token builtin class-name">printf</span> <span class="token string">"<span class="token variable">$FM1</span> <span class="token variable">$FM2</span>"</span> <span class="token string">"<span class="token variable">$IDX</span>"</span> <span class="token variable">$CHR</span><span class="token punctuation">;</span> <span class="token variable"><span class="token punctuation">((</span> <span class="token punctuation">(</span>IDX<span class="token operator">+=</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token operator">%</span><span class="token number">8</span><span class="token punctuation">))</span></span><span class="token operator">||</span><span class="token builtin class-name">echo</span> <span class="token string">'|'</span>
   <span class="token keyword">done</span>

<span class="token builtin class-name">exit</span> <span class="token variable">$?</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>例 T-3. 第三个 ASCII 表脚本，使用 <em>awk</em></p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token shebang important">#!/bin/bash</span>
<span class="token comment"># ASCII table script, using awk.</span>
<span class="token comment"># Author: Joseph Steinhauser</span>
<span class="token comment"># Used in ABS Guide with permission.</span>


<span class="token comment">#-------------------------------------------------------------------------</span>
<span class="token comment">#-- File:  ascii     Print ASCII chart, base 10/8/16         (JETS-2010)</span>
<span class="token comment">#-------------------------------------------------------------------------</span>
<span class="token comment">#-- Usage: ascii [oct|dec|hex|help|8|10|16]</span>
<span class="token comment">#--</span>
<span class="token comment">#-- This script prints a summary of ASCII char codes from Zero to 127.</span>
<span class="token comment">#-- Numeric values may be printed in Base10, Octal, or Hex (Base16).</span>
<span class="token comment">#--</span>
<span class="token comment">#-- Format Based on: /usr/share/lib/pub/ascii with base-10 as default.</span>
<span class="token comment">#-- For more detail, man ascii</span>
<span class="token comment">#-------------------------------------------------------------------------</span>

<span class="token punctuation">[</span> <span class="token parameter variable">-n</span> <span class="token string">"<span class="token environment constant">$BASH_VERSION</span>"</span> <span class="token punctuation">]</span> <span class="token operator">&amp;&amp;</span> <span class="token builtin class-name">shopt</span> <span class="token parameter variable">-s</span> extglob

<span class="token keyword">case</span> <span class="token string">"<span class="token variable">$1</span>"</span> <span class="token keyword">in</span>
   oct<span class="token operator">|</span><span class="token punctuation">[</span>Oo<span class="token punctuation">]</span>?<span class="token punctuation">(</span><span class="token punctuation">[</span>Cc<span class="token punctuation">]</span><span class="token punctuation">[</span>Tt<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">|</span><span class="token number">8</span><span class="token punctuation">)</span>       <span class="token assign-left variable">Obase</span><span class="token operator">=</span>Octal<span class="token punctuation">;</span>  <span class="token assign-left variable">Numy</span><span class="token operator">=</span>3o<span class="token punctuation">;</span><span class="token punctuation">;</span>
   hex<span class="token operator">|</span><span class="token punctuation">[</span>Hh<span class="token punctuation">]</span>?<span class="token punctuation">(</span><span class="token punctuation">[</span>Ee<span class="token punctuation">]</span><span class="token punctuation">[</span>Xx<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">|</span><span class="token number">16</span><span class="token operator">|</span><span class="token punctuation">[</span>Xx<span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token assign-left variable">Obase</span><span class="token operator">=</span>Hex<span class="token punctuation">;</span>    <span class="token assign-left variable">Numy</span><span class="token operator">=</span>2X<span class="token punctuation">;</span><span class="token punctuation">;</span>
   <span class="token builtin class-name">help</span><span class="token operator">|</span>?<span class="token punctuation">(</span>-<span class="token punctuation">)</span><span class="token punctuation">[</span>h?<span class="token punctuation">]</span><span class="token punctuation">)</span>        <span class="token function">sed</span> <span class="token parameter variable">-n</span> <span class="token string">'2,/^[ ]*$/p'</span> <span class="token variable">$0</span><span class="token punctuation">;</span><span class="token builtin class-name">exit</span><span class="token punctuation">;</span><span class="token punctuation">;</span>
   code<span class="token operator">|</span><span class="token punctuation">[</span>Cc<span class="token punctuation">]</span><span class="token punctuation">[</span>Oo<span class="token punctuation">]</span><span class="token punctuation">[</span>Dd<span class="token punctuation">]</span><span class="token punctuation">[</span>Ee<span class="token punctuation">]</span><span class="token punctuation">)</span>sed <span class="token parameter variable">-n</span> <span class="token string">'/case/,$p'</span>   <span class="token variable">$0</span><span class="token punctuation">;</span><span class="token builtin class-name">exit</span><span class="token punctuation">;</span><span class="token punctuation">;</span>
   *<span class="token punctuation">)</span> <span class="token assign-left variable">Obase</span><span class="token operator">=</span>Decimal
<span class="token keyword">esac</span>
<span class="token builtin class-name">export</span> Obase   <span class="token comment"># CODE is actually shorter than the chart!</span>

<span class="token function">awk</span> <span class="token string">'BEGIN{print "\n\t\t## "ENVIRON["Obase"]" ASCII Chart ##\n"
           ab="soh,stx,etx,eot,enq,ack,bel,bs,tab,nl,vt,np,cr,so,si,dle,"
           ad="dc1,dc2,dc3,dc4,nak,syn,etb,can,em,sub,esc,fs,gs,rs,us,sp"
           split(ab ad,abr,",");abr[0]="nul";abr[127]="del";
           fm1="|%0'</span>"<span class="token variable">${Numy<span class="token operator">:-</span> 4d}</span><span class="token string">"' %-3s"</span>
           for<span class="token punctuation">(</span>idx<span class="token operator">=</span><span class="token number">0</span><span class="token punctuation">;</span>idx<span class="token operator">&lt;</span><span class="token number">128</span><span class="token punctuation">;</span>idx++<span class="token punctuation">)</span><span class="token punctuation">{</span>fmt<span class="token operator">=</span>fm1 <span class="token punctuation">(</span>++colz%8?<span class="token string">""</span><span class="token builtin class-name">:</span><span class="token string">"|<span class="token entity" title="\n">\n</span>"</span><span class="token punctuation">)</span>
           printf<span class="token punctuation">(</span>fmt,idx,<span class="token punctuation">(</span>idx <span class="token keyword">in</span> abr<span class="token punctuation">)</span>?abr<span class="token punctuation">[</span>idx<span class="token punctuation">]</span>:sprintf<span class="token punctuation">(</span><span class="token string">"%c"</span>,idx<span class="token punctuation">))</span><span class="token punctuation">}</span> <span class="token punctuation">}</span>'

<span class="token builtin class-name">exit</span> <span class="token variable">$?</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


