module.exports = [
  "",
  {
    title: "1 Python 简介",
    collapsable: false,
    children: ["first", "codeSpecification", "python-virtualenv", "python-pip"]
  },
  "python-basic-grammar.md",
  "python-linear-data-structure.md",
  "python-ha-tables-analytic-expre.md",
  "python-function.md",
  "python-decorator.md",
  "python-dir-file-pro.md",
  "python-serialize.md",
  "python-exception.md",
  "python-oo-package.md",
  "python-oo-inher-pol.md",
  "python-magic.md",
  "python-thread.md",
  "python-thread-sync.md",
  "python-gil-multiprocessing.md",
  "python-tcp-pg.md",
  "python-socketserver.md",
  "python-io-model.md",
  "python-instance",
]