module.exports = {
  zh: {
    "/basic/system/": require("./basic/system"),
    "/basic/network/": require("./basic/network"),
    "/code/shell/": require("./code/shell"),
    "/code/python/": require("./code/python"),
    "/code/golang/": require("./code/golang"),
    "/code/frontend/": require("./code/frontend"),
    "/cloudnative/docker/": require("./cloudnative/docker"),
    "/cloudnative/kubernetes/": require("./cloudnative/kubernetes"),
    "/automate/ansible/": require("./automate/ansible"),
    "/automate/jenkins/": require("./automate/jenkins"),
    "/web/nginx/": require("./web/nginx"),
    "/web/django/": require("./web/django"),
    "/monitor/zabbix/": require("./monitor/zabbix"),
    "/monitor/elk/": require("./monitor/elk"),
    "/db/mysql/": require("./db/mysql"),
    "/db/redis/": require("./db/redis"),
    "/linux/basic/": require("./linux/basic"),
  },
};